all: ../bin/admin ../bin/expire ../bin/unexpire ../bin/queue ../bin/request ../bin/add ../bin/user_request
../bin/admin: admin.c
	gcc -o ../bin/admin admin.c
../bin/expire: expire.c
	gcc -o ../bin/expire expire.c
../bin/unexpire: unexpire.c
	gcc -o ../bin/unexpire unexpire.c
../bin/queue: queue.c
	gcc -o ../bin/queue queue.c
../bin/request: request.c
	gcc -o ../bin/request request.c
../bin/add: useradd.c
	gcc -o ../bin/add useradd.c
../bin/userlist: users.c
	gcc -o ../bin/userlist users.c
../bin/user_request: user_request.c
	gcc -o ../bin/user_request user_request.c
